const $=id=>document.getElementById(id);const ns='http://www.w3.org/2000/svg';
const words={ar:{brand:'غرفة التكتيك',eyebrow:'مساحة التحليل المشترك',title:'خطة واحدة. رؤية مشتركة.',subtitle:'حرّك اللاعبين، ارسم المسارات، وناقش الخطوة التالية مع فريقك.',share:'نسخ رابط الغرفة ↗',board:'لوحة التكتيك',formation:'كرة القدم · 11 ضد 11',home:'الفريق A',away:'الفريق B',move:'↖ تحريك',arrow:'↗ سهم تكتيكي',clear:'مسح الأسهم',export:'تنزيل الخطة ↓',hint:'اسحب اللاعبين والكرة. اختر السهم ثم اسحب لرسم مسار.',player:'اسم اللاعب',save:'حفظ',room:'غرفة التحليل',yourname:'اسمك',server:'عنوان الخادم',serverhint:'اتركه فارغًا عند فتح الموقع من خادم Python.',create:'إنشاء غرفة مشتركة',code:'رمز الغرفة',join:'انضمام',discussion:'مناقشة الخطة',send:'إرسال',footer:'مساحة للأفكار التي تصنع الفارق',privacy:'رابط الغرفة يمنح صلاحية التعديل · شاركه مع فريقك فقط',local:'تجربة محلية',online:'متصل مباشرة',connecting:'جارٍ الاتصال',offline:'انقطع الاتصال — أعد الانضمام',empty:'أنشئ غرفة أو انضم إلى فريقك لبدء النقاش.',placeholder:'شارك ملاحظة تكتيكية…',error:'تعذر الاتصال. تحقق من الخادم ورمز الغرفة.',copied:'تم نسخ رابط الغرفة',needroom:'أنشئ غرفة مشتركة أولًا',clearconfirm:'مسح جميع الأسهم للفريق؟',invalid:'عنوان الخادم غير صحيح',failed:'تعذّر تنفيذ العملية',keyboard:'استخدم مفاتيح الأسهم لتحريك العنصر',ready:'الغرفة جاهزة. شارك الرابط مع فريقك.'},en:{brand:'TACTICAL ROOM',eyebrow:'SHARED ANALYSIS WORKSPACE',title:'One plan. Shared vision.',subtitle:'Move your players, map the next pass, and work through it together.',share:'Copy room link ↗',board:'Tactical board',formation:'Football · 11 vs 11',home:'Team A',away:'Team B',move:'↖ Move',arrow:'↗ Tactical arrow',clear:'Clear arrows',export:'Export plan ↓',hint:'Drag players and the ball. Select Arrow, then drag to draw a path.',player:'Player name',save:'Save',room:'Analysis room',yourname:'Your name',server:'Server address',serverhint:'Leave blank when using the Python server directly.',create:'Create shared room',code:'Room code',join:'Join',discussion:'Team discussion',send:'Send',footer:'SPACE FOR THE NEXT GOOD IDEA',privacy:'Room links grant editing access · Share only with your team',local:'Local practice',online:'Connected live',connecting:'Connecting',offline:'Disconnected — join again',empty:'Create a room or join your team to start the discussion.',placeholder:'Share a tactical thought…',error:'Could not connect. Check the server and room code.',copied:'Room link copied',needroom:'Create a shared room first',clearconfirm:'Clear all tactical arrows for everyone?',invalid:'Invalid server address',failed:'Could not apply this action',keyboard:'Use arrow keys to move',ready:'Room ready. Share the link with your team.'}};
let lang=localStorage.getItem('tactica-lang')||'ar';let mode='move',socket=null,connection='local',room='',participants=[],drag=null;
const formation=[[7,50],[24,15],[24,38],[24,62],[24,85],[42,24],[37,50],[42,76],[61,18],[65,50],[61,82]];
let state={players:['a','b'].flatMap(team=>formation.map(([x,y],i)=>({id:team+i,x:team==='a'?x:100-x,y,team,number:i+1,name:''}))),ball:{x:50,y:50},arrows:[],messages:[],revision:0};
const tr=k=>words[lang][k];function toast(t){$('toast').textContent=t;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',4000)}
function translate(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i]').forEach(e=>e.textContent=tr(e.dataset.i));$('language').textContent=lang==='ar'?'English':'العربية';$('message').placeholder=tr('placeholder');$('status').textContent=tr(connection);$('language').setAttribute('aria-label','Change language');render()}
$('language').onclick=()=>{lang=lang==='ar'?'en':'ar';localStorage.setItem('tactica-lang',lang);translate()};
function svg(tag,attrs,text){const e=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e}
function render(){
 $('players').replaceChildren();state.players.forEach(p=>{const g=svg('g',{'data-id':p.id,transform:`translate(${p.x*10.5},${p.y*6.8})`,tabindex:0,role:'button','aria-label':`${p.team.toUpperCase()} ${p.number} ${p.name}. ${tr('keyboard')}`});g.append(svg('circle',{r:18,fill:p.team==='a'?'#d6efb2':'#e9ac89',stroke:'#112e27','stroke-width':3}),svg('text',{'text-anchor':'middle','dominant-baseline':'central',fill:'#162c27','font-size':17,'font-weight':700},p.number));if(p.name)g.append(svg('text',{y:34,'text-anchor':'middle',fill:'white','font-size':14,stroke:'#10271f','stroke-width':3,'paint-order':'stroke'},p.name));$('players').append(g)});
 $('ball').replaceChildren(svg('circle',{cx:state.ball.x*10.5,cy:state.ball.y*6.8,r:11,fill:'#fff',stroke:'#142b23','stroke-width':3}),svg('circle',{cx:state.ball.x*10.5,cy:state.ball.y*6.8,r:4,fill:'#142b23'}));$('ball').dataset.id='ball';$('ball').setAttribute('tabindex','0');$('ball').setAttribute('role','button');$('ball').setAttribute('aria-label',lang==='ar'?'الكرة':'Ball');
 $('arrows').replaceChildren();state.arrows.forEach(a=>$('arrows').append(svg('line',{x1:a.x*10.5,y1:a.y*6.8,x2:a.x2*10.5,y2:a.y2*6.8,stroke:'#f5cf72','stroke-width':4,'stroke-dasharray':'10 5','marker-end':'url(#tip)'})));
 const selected=$('player').value;$('player').replaceChildren();state.players.forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=`${p.team.toUpperCase()} · ${p.number}${p.name?' '+p.name:''}`;$('player').append(o)});if(selected)$('player').value=selected;
 $('revision').textContent='#'+String(state.revision).padStart(3,'0');$('count').textContent=participants.length||1;$('people').replaceChildren();participants.forEach(name=>{const e=document.createElement('span');e.textContent=name;$('people').append(e)});
 const signature=JSON.stringify(state.messages)+lang;if(render.signature!==signature){render.signature=signature;$('messages').replaceChildren();if(!state.messages.length){const p=document.createElement('p');p.className='empty';p.textContent=tr('empty');$('messages').append(p)}state.messages.forEach(m=>{const d=document.createElement('div');d.className='message';const n=document.createElement('strong');n.textContent=m.name;const p=document.createElement('p');p.textContent=m.text;d.append(n,p);$('messages').append(d)});$('messages').scrollTop=$('messages').scrollHeight}
 $('message').disabled=connection!=='online';$('chat').querySelector('button').disabled=connection!=='online';
}
function emit(data){if(connection==='online'&&socket?.readyState===WebSocket.OPEN){socket.send(JSON.stringify(data));return true}if(connection!=='local'){toast(tr('offline'));return false}if(data.type==='move'){const p=data.id==='ball'?state.ball:state.players.find(p=>p.id===data.id);Object.assign(p,{x:data.x,y:data.y})}else if(data.type==='arrow'){if(state.arrows.length>=150)return false;state.arrows.push(data)}else if(data.type==='clear')state.arrows=[];else if(data.type==='rename')state.players.find(p=>p.id===data.id).name=data.name;state.revision++;render();return true}
function point(e){const p=new DOMPoint(e.clientX,e.clientY).matrixTransform($('pitch').getScreenCTM().inverse());return{x:Math.max(2,Math.min(98,p.x/10.5)),y:Math.max(2,Math.min(98,p.y/6.8))}}
$('pitch').onpointerdown=e=>{if(e.button!==0)return;const id=e.target.closest('[data-id]')?.dataset.id;if(mode==='move'&&!id)return;drag={id,start:point(e),last:0};$('pitch').setPointerCapture(e.pointerId);e.preventDefault()};
$('pitch').onpointermove=e=>{if(!drag)return;const p=point(e);if(mode==='move'){if(performance.now()-drag.last>65){drag.last=performance.now();emit({type:'move',id:drag.id,...p})}}else{let preview=$('preview');if(!preview){preview=svg('line',{id:'preview',stroke:'#ffe39a','stroke-width':4,'marker-end':'url(#tip)'});$('pitch').append(preview)}Object.entries({x1:drag.start.x*10.5,y1:drag.start.y*6.8,x2:p.x*10.5,y2:p.y*6.8}).forEach(([k,v])=>preview.setAttribute(k,v))}};
$('pitch').onpointerup=e=>{if(!drag)return;const p=point(e);if(mode==='move')emit({type:'move',id:drag.id,...p});else if(Math.hypot(p.x-drag.start.x,p.y-drag.start.y)>2)emit({type:'arrow',...drag.start,x2:p.x,y2:p.y});drag=null;$('preview')?.remove()};$('pitch').onpointercancel=()=>{drag=null;$('preview')?.remove()};
$('pitch').onkeydown=e=>{const delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];const id=e.target.closest('[data-id]')?.dataset.id;if(!delta||!id)return;e.preventDefault();const p=id==='ball'?state.ball:state.players.find(p=>p.id===id);emit({type:'move',id,x:Math.max(2,Math.min(98,p.x+delta[0])),y:Math.max(2,Math.min(98,p.y+delta[1]))});document.querySelector(`[data-id="${id}"]`)?.focus()};
for(const id of ['move','arrow'])$(id).onclick=()=>{mode=id;['move','arrow'].forEach(k=>$(k).classList.toggle('active',k===id));$('pitch').style.cursor=id==='arrow'?'crosshair':'default'};
$('clear').onclick=()=>{if(confirm(tr('clearconfirm')))emit({type:'clear'})};$('player').onchange=()=>{$('playerName').value=state.players.find(p=>p.id===$('player').value)?.name||''};$('rename').onclick=()=>emit({type:'rename',id:$('player').value,name:$('playerName').value.trim().slice(0,24)});
function server(){const value=$('endpoint').value.trim();const url=new URL(value||location.origin);if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw Error();return url.origin}
function connect(key){if(!/^[\w-]{24}$/.test(key)){toast(tr('error'));return}let base;try{base=server()}catch{toast(tr('invalid'));return}socket?.close();connection='connecting';translate();const ws=new WebSocket(base.replace(/^http/,'ws')+'/ws/'+key+'?name='+encodeURIComponent($('name').value.trim()||'Analyst'));socket=ws;const timer=setTimeout(()=>{if(ws.readyState===WebSocket.CONNECTING)ws.close()},10000);ws.onopen=()=>{if(socket!==ws)return;clearTimeout(timer);connection='online';room=key;$('roomCode').value=key;const hash=new URLSearchParams({room:key,server:base});history.replaceState(null,'','#'+hash);translate();toast(tr('ready'))};ws.onmessage=e=>{if(socket!==ws)return;const data=JSON.parse(e.data);if(data.type==='state'){state=data.state;participants=data.participants;render()}else toast(tr('failed'))};ws.onclose=()=>{clearTimeout(timer);if(socket!==ws)return;connection='offline';translate()};ws.onerror=()=>{if(socket===ws)toast(tr('error'))}}
$('create').onclick=async()=>{const button=$('create');button.disabled=true;try{const response=await fetch(server()+'/api/rooms',{method:'POST',signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error();connect((await response.json()).room)}catch{toast(tr('error'))}finally{button.disabled=false}};$('join').onclick=()=>connect($('roomCode').value.trim());
$('share').onclick=async()=>{if(!room){toast(tr('needroom'));return}try{await navigator.clipboard.writeText(location.href);toast(tr('copied'))}catch{prompt(tr('share'),location.href)}};
$('chat').onsubmit=e=>{e.preventDefault();const text=$('message').value.trim();if(text&&emit({type:'chat',text}))$('message').value=''};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='tactica-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
const params=new URLSearchParams(location.hash.slice(1));if(params.get('server'))$('endpoint').value=params.get('server');if(params.get('room'))$('roomCode').value=params.get('room');translate();
